# API Piclist Concatenation Code

### Team retrieve lists of cover art images from theGamesDB.net using both Platform and Art API's.  This code concatenates all of the piclists within folder into a single dataframe containing all available cover art image links for all platforms and saves as master_piclist.csv to be used with further analysis.

In [21]:
import pandas as pd
import os

In [22]:
# Get current directory
os.getcwd()

'/Users/ianwomack/UTAAU201710DATA1-Class-Repository-DATA/Projects/Final_Project/mosaic_images/piclists'

In [23]:
# Loop through folder and read all csv files to merge

files = [f for f in os.listdir('.') if os.path.isfile(f)]

merged = []

for f in files:
    filename, ext = os.path.splitext(f)
    if ext == '.csv':
        read = pd.read_csv(f)
        merged.append(read)

result = pd.concat(merged)

result.head()

,id,GameTitle,ReleaseDate,thumb,Platform
0,3373,Dark Arena,1/18/02,boxart/original/front/3373-1.jpg,GBA
1,3374,Dave Mirra Freestyle BMX 2,11/25/01,boxart/original/front/3374-1.jpg,GBA
2,3375,Davis Cup Tennis,10/14/02,boxart/original/front/3375-1.jpg,GBA
3,198,Classic NES Series: Zelda II: The Adventure of...,10/25/04,boxart/original/front/198-1.jpg,GBA
4,45987,Dragon Drive: World D Break,7/18/03,boxart/original/front/45987-1.jpg,GBA

In [24]:
# Count results by platform
result.Platform.value_counts()

PS2       2559
PS        2110
SNES      1903
DS        1867
PS3       1825
NES       1710
GBA       1671
X360      1642
Wii       1585
G         1467
PC        1296
PSP       1138
PS4       1116
GEN       1062
X          945
2600       801
GC         673
XOne       561
3DS        530
SAT        529
PSV        482
N64        416
GG         380
DC         378
WiiU       322
SCD        230
3DO        203
SWITCH     191
Int        167
Name: Platform, dtype: int64

In [25]:
# Count results in all columns
result.count()

id             29759
GameTitle      29759
ReleaseDate    27170
thumb          29585
Platform       29759
dtype: int64

In [28]:
# Rename columns and set index to gdb_id

result = result.rename(columns={'id':'gdb_id', 'GameTitle':'Title', 'ReleaseDate':'Release_Date', 'thumb':'Thumb', 'Platform':'Platform'})

result.set_index('gdb_id', inplace=True)

result.head()

,Title,Release_Date,Thumb,Platform
gdb_id,,,,
3373,Dark Arena,1/18/02,boxart/original/front/3373-1.jpg,GBA
3374,Dave Mirra Freestyle BMX 2,11/25/01,boxart/original/front/3374-1.jpg,GBA
3375,Davis Cup Tennis,10/14/02,boxart/original/front/3375-1.jpg,GBA
198,Classic NES Series: Zelda II: The Adventure of...,10/25/04,boxart/original/front/198-1.jpg,GBA
45987,Dragon Drive: World D Break,7/18/03,boxart/original/front/45987-1.jpg,GBA

In [31]:
# Copy dataframe
master_df = result

master_df.head()

,Title,Release_Date,Thumb,Platform
gdb_id,,,,
3373,Dark Arena,1/18/02,boxart/original/front/3373-1.jpg,GBA
3374,Dave Mirra Freestyle BMX 2,11/25/01,boxart/original/front/3374-1.jpg,GBA
3375,Davis Cup Tennis,10/14/02,boxart/original/front/3375-1.jpg,GBA
198,Classic NES Series: Zelda II: The Adventure of...,10/25/04,boxart/original/front/198-1.jpg,GBA
45987,Dragon Drive: World D Break,7/18/03,boxart/original/front/45987-1.jpg,GBA

In [34]:
# Create full links from thumb cover back links

base_url = "http://thegamesdb.net/banners/"

master_df['URL'] = base_url + master_df['Thumb'].astype(str)

master_df.head()

,Title,Release_Date,Thumb,Platform,URL
gdb_id,,,,,
3373,Dark Arena,1/18/02,boxart/original/front/3373-1.jpg,GBA,http://thegamesdb.net/banners/boxart/original/...
3374,Dave Mirra Freestyle BMX 2,11/25/01,boxart/original/front/3374-1.jpg,GBA,http://thegamesdb.net/banners/boxart/original/...
3375,Davis Cup Tennis,10/14/02,boxart/original/front/3375-1.jpg,GBA,http://thegamesdb.net/banners/boxart/original/...
198,Classic NES Series: Zelda II: The Adventure of...,10/25/04,boxart/original/front/198-1.jpg,GBA,http://thegamesdb.net/banners/boxart/original/...
45987,Dragon Drive: World D Break,7/18/03,boxart/original/front/45987-1.jpg,GBA,http://thegamesdb.net/banners/boxart/original/...

In [35]:
# Save merged dataframe as master_piclist
master_df.to_csv("../master_piclist.csv")

In [37]:
# Drop Thumb column
master_clean = master_df.drop('Thumb', 1)

master_clean.head()

,Title,Release_Date,Platform,URL
gdb_id,,,,
3373,Dark Arena,1/18/02,GBA,http://thegamesdb.net/banners/boxart/original/...
3374,Dave Mirra Freestyle BMX 2,11/25/01,GBA,http://thegamesdb.net/banners/boxart/original/...
3375,Davis Cup Tennis,10/14/02,GBA,http://thegamesdb.net/banners/boxart/original/...
198,Classic NES Series: Zelda II: The Adventure of...,10/25/04,GBA,http://thegamesdb.net/banners/boxart/original/...
45987,Dragon Drive: World D Break,7/18/03,GBA,http://thegamesdb.net/banners/boxart/original/...